version: "3.8"
services:
  dcs-postgres:
    image: postgres:latest
    container_name: go-postgres
    restart: always
    environment:
      POSTGRES_USER: mustty
      POSTGRES_PASSWORD: mypass132
      POSTGRES_DB: gopportunities
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
